### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by TheDrive2** [dtweston/Netopsy#2]
1. Thank you for App! MacOS looks poor without many useful app's support!
2. Please provide independent download location!
If you do NOT want to publish sources, OK that's your choice and no problem.
But please ALWAYS publish at least binaries at the independent platforms!
E.g. you can upload them here, at the separate Releases folder. It would be nice.
Big corps force you and me and the whole big world to use their 'marketplaces'. We did lived for decades without any marketplaces at all. There were no problems with it. There are still exist people around who do not use them and never will. I do NOT have any Google or Apple or Microsoft device associated accounts. AT ALL!
I have a few absolutely separate, absolutely anonymous Google and Apple and Microsoft accounts which I do use exclusively to explore, hack and development of absolutely independent projects.
If you will ask me how do I use iOS related devices, I can answer you I DO NOT USE them for personal needs, just for hacking and helping people. There is a small problem to use MacOS, Windows, Android without any accounts. Trust me. There is a small problem to cut off most compromising techs from there.
No one can not cut off mask ROM located bootloader signature checks from iOS devices, thus any jailbreaks never will be stable (since iP 3GS) and I can not use them for personal needs at all. And also... I'm not alone. Many people around share the idea. We are not the Matrix slaves, sir! Thank you for understanding.

**Comment by dtweston** [comment]
Thanks for your interest!

I think that's a reasonable request, and I'll look into the Github Releases feature to accomplish that.

**Comment by dtweston** [comment]
I've added a release for v1.2.0 here: https://github.com/dtweston/netopsy/releases/tag/v1.2.0
